language: android
jdk:
  - oraclejdk8
android:
  components:
    - android-28
    - build-tools-28.0.2
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
  - chmod +x gradlew
script:
  - ./gradlew desktop:dist
before_install:
    - yes | sdkmanager "build-tools;28.0.2"