jdk:
  - openjdk8
env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_ABI=armeabi-v7a
dist: xenial
language: android
android:
  components:
    - tools
    - build-tools-29.0.3
    - android-30
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-30"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_script:
  - chmod +x gradlew
script:
  - ./gradlew desktop:buildLite
  - ./gradlew desktop:buildFull
  - ./gradlew android:assembleLiteRelease
  - ./gradlew android:assembleFullRelease