language: android
jdk:
  - openjdk8
  - oraclejdk8
android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
  - chmod +x gradlew
script:
  - ./gradlew desktop:distLite
  - ./gradlew desktop:distFull
  - ./gradlew android:assembleRelease
before_install:
    - yes | sdkmanager "build-tools;28.0.3"